services:
    db:
        image: postgres:alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data_quiz:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=quiz

volumes:
    postgres_data_quiz:
